--liquibase formatted sql
--changeset chinazom.nnoli:03.03.20.20.15

INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('UNDERWEAR', 1000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('SHIRT', 2000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('T_SHIRT', 2000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('JEANS', 3000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('TROUSER', 2000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('SKIRT', 2000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('SUIT', 5000);
INSERT INTO LAUNDRY_ITEM
(ITEM, COST)
VALUES('NATIVE', 1500);